name: MMOStats
version: '1.0-SNAPSHOT'
main: com.klrir.mmoStats.MMOStats
api-version: '1.21'
softdepend: [ ProtocolLib ]
commands:
  e:
  stats:
  glow:
  statsystem:
    description: "Ativar/Desativar o sistema de Status"
    usage: "/statsystem"